### ISSUE TITLE
wrong State Previewing when Onresume() eccured

### ISSUE THREAD

**Issue by jriporter** [Nightonke/WoWoViewPager#2]
Hi Tnx for developing this amazing Library .
there is one problem in loading views on wowViepager instance e.g start app then swiping view then  press Home in order to pause and then Resume activity if you follow this order see the problem

**Comment by Nightonke** [comment]
I will check this as soon as possible.

**Comment by jriporter** [comment]
this problem happens  On app_intro_example Activity please check it,
thanks in advanced
