### ISSUE TITLE
animations reset when I pause the app

### ISSUE THREAD

**Issue by mneckoee** [Nightonke/WoWoViewPager#6]
Hi,
even in sample app if I go to second page then touch home button on device, and then return to app again, animation in first page get something odd! try it!

**Comment by Nightonke** [comment]
I will try and fix this. Thanks for reporting.

**Comment by mneckoee** [comment]
Hi, I found out why it occurs, we add animation onWindowsFocusChanged, if we add them in OnCreate method the problem will disappear. because OnWindowsFocusChanged is called several time.
