### ISSUE TITLE
Vertical scrolling

### ISSUE THREAD

**Issue by trieulh-ict** [Nightonke/WoWoViewPager#8]
Awesome lib, man. I have a question about vertical scrolling ? is your lib support it?

Thank in advance.

**Comment by Nightonke** [comment]
@trieulh-ict Sorry for replying so late. Now version 2.0.0 and above supports [vertical scrolling](https://github.com/Nightonke/WoWoViewPager/wiki/WoWoViewPager-Attributes#direction).
